sudo: required

language: bash
script:
  - mkdir bundles
  - cp README.md bundles/
  - tar czvf bundles/bidule.tgz README.md

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y vim 
  
jobs:
  include:
    - stage: buildbase
      script: echo "buildlol"
    - stage: make deb
      script: echo "make deb"
    - stage: deploy release
      deploy:
        provider: releases
        file_glob: true
        api_key: $GITHUB_OAUTH_TOKEN
        file: bundles/*
        skip_cleanup: true
        draft: true
